name: lpro2_quiz
description: "تطبيق دوري العقارات المطور لمريم - نسخة بريميوم"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  # الخطوط وتنسيق النصوص
  google_fonts: ^6.1.0
  
  # الأيقونات
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.6.0
  
  # تشغيل ملفات SVG (اللوجو)
  flutter_svg: ^2.0.10

  # منظومة الفايربيز الأساسية (بدون Storage)
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0

  # أدوات المشاركة والوقت
  share_plus: ^12.0.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

# إعدادات أيقونة التطبيق
flutter_launcher_icons:
  android: true 
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 
  adaptive_icon_background: "#1B4D57" 
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true

  # تعريف الملفات الموجودة في مجلد assets
  assets:
    - assets/logo.svg
    - assets/top_brand.png
    - assets/icon.png
    - assets/card_images/