name: lpro2_quiz
description: "تطبيق دوري العقارات المطور لمريم"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # دعم اللغة العربية
  flutter_localizations:
    sdk: flutter

  # خطوط جوجل (Cairo)
  google_fonts: ^6.1.0

  # أيقونات إضافية
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.6.0

  # مكتبة تشغيل صور الـ SVG (مهمة عشان logo.svg)
  flutter_svg: ^2.0.10

  # مكتبات الفايربيز
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # إعداد الصور الموجودة فعلياً في مجلد assets
  assets:
    - assets/logo.svg
    - assets/top_brand.png
    - assets/icon.png